### ISSUE TITLE
Small inconsistency with switches

### ISSUE THREAD

**Issue by sadn1ck** [USBA/macOS11-theme#4]
## When on:
![image](https://user-images.githubusercontent.com/16396161/86580201-05b87700-bf9c-11ea-8de9-69ae5bad6c7b.png)

## When off: 
![image](https://user-images.githubusercontent.com/16396161/86580244-149f2980-bf9c-11ea-80a5-1072ff68a73e.png)

**Comment by Tuxman2** [comment]
@sadn1ck: I've got the same problem. :-(

I love this theme. Hope it will be fixed soon.
